language: ruby
#os: osx
rvm:
  - 2.2
  - jruby
  - truffleruby
script:
  - cd ./client
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
  - ruby test.rb
